(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"pandemic_atlas_1", frames: [[0,0,208,207],[210,0,208,207],[420,0,208,207],[630,0,208,207],[0,209,208,207],[0,418,208,207],[0,627,208,207],[210,209,208,207],[420,209,208,207],[630,209,208,207],[210,418,208,207],[210,627,208,207],[420,418,208,207],[630,418,208,207],[420,627,208,207],[630,627,208,207]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_73 = function() {
	this.initialize(ss["pandemic_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_72 = function() {
	this.initialize(ss["pandemic_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_71 = function() {
	this.initialize(ss["pandemic_atlas_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_70 = function() {
	this.initialize(ss["pandemic_atlas_1"]);
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_69 = function() {
	this.initialize(ss["pandemic_atlas_1"]);
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_68 = function() {
	this.initialize(ss["pandemic_atlas_1"]);
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_67 = function() {
	this.initialize(ss["pandemic_atlas_1"]);
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_66 = function() {
	this.initialize(ss["pandemic_atlas_1"]);
	this.gotoAndStop(7);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_65 = function() {
	this.initialize(ss["pandemic_atlas_1"]);
	this.gotoAndStop(8);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_64 = function() {
	this.initialize(ss["pandemic_atlas_1"]);
	this.gotoAndStop(9);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_63 = function() {
	this.initialize(ss["pandemic_atlas_1"]);
	this.gotoAndStop(10);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_62 = function() {
	this.initialize(ss["pandemic_atlas_1"]);
	this.gotoAndStop(11);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_61 = function() {
	this.initialize(ss["pandemic_atlas_1"]);
	this.gotoAndStop(12);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_60 = function() {
	this.initialize(ss["pandemic_atlas_1"]);
	this.gotoAndStop(13);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_59 = function() {
	this.initialize(ss["pandemic_atlas_1"]);
	this.gotoAndStop(14);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_58 = function() {
	this.initialize(ss["pandemic_atlas_1"]);
	this.gotoAndStop(15);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_75 = function() {
	this.initialize(img.CachedBmp_75);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,2832,992);


(lib.Tween16 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_73();
	this.instance.setTransform(-52.1,-51.85,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-51.8,104,103.5);


(lib.Tween15 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_72();
	this.instance.setTransform(-52.1,-51.85,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-51.8,104,103.5);


(lib.Tween14 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_71();
	this.instance.setTransform(-52.1,-51.85,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-51.8,104,103.5);


(lib.Tween13 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_70();
	this.instance.setTransform(-52.1,-51.85,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-51.8,104,103.5);


(lib.Tween12 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_69();
	this.instance.setTransform(-52.1,-51.85,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-51.8,104,103.5);


(lib.Tween11 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_68();
	this.instance.setTransform(-52.1,-51.85,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-51.8,104,103.5);


(lib.Tween10 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_67();
	this.instance.setTransform(-52.1,-51.85,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-51.8,104,103.5);


(lib.Tween9 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_66();
	this.instance.setTransform(-52.1,-51.85,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-51.8,104,103.5);


(lib.Tween8 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_65();
	this.instance.setTransform(-52.1,-51.85,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-51.8,104,103.5);


(lib.Tween7 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_64();
	this.instance.setTransform(-52.1,-51.85,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-51.8,104,103.5);


(lib.Tween6 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_63();
	this.instance.setTransform(-52.1,-51.85,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-51.8,104,103.5);


(lib.Tween5 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_62();
	this.instance.setTransform(-52.1,-51.85,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-51.8,104,103.5);


(lib.Tween4 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_61();
	this.instance.setTransform(-52.1,-51.85,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-51.8,104,103.5);


(lib.Tween3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_60();
	this.instance.setTransform(-52.1,-51.85,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-51.8,104,103.5);


(lib.Tween2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_59();
	this.instance.setTransform(-52.1,-51.85,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-51.8,104,103.5);


(lib.Tween1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_58();
	this.instance.setTransform(-52.1,-51.85,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-52.1,-51.8,104,103.5);


(lib.covidspots = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.CachedBmp_75();
	this.instance.setTransform(11.1,-268.8,0.5,0.5);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#5B075F").s().p("Eg5vAmuQgMgFgJgLQgIgJgCgIQgCgLAEgOIAFgKQAGgKALgFQAKgFALABIAAgDQAVAHAIAHQAJAHADANQAEALgDAMQgCAMgIAKQgIAJgMAEIgJABQgIAAgJgDgEg1sAi8QgHgFgHgKQgIgJAAgIQgBgDADgKIACgMQACgFAGgGQASgSAQAFIAAgEQAOACALAJQAMAJAEANQAEANgDAPQgEAOgLAIQgLAJgOAAIgCAAQgOAAgKgHgEgqhAifQgJgFgLgPQgGgJAAgHIACgMIACgLQABgEAGgHQAUgTAPAFIAAgDQAPABAMALQALAKAEAOQADANgEAMQgEANgJAIQgKAJgNABIgFABQgLAAgJgGgEgz9Ah9QgFgDgKgMQgIgLAAgHIACgNIACgLQACgFAGgGQATgTAQAGIAAgEQANACAMAJQALAJAEAMQAFAOgEAOQgDAOgLAJQgKAJgPAAIgDAAQgNAAgKgHgEgxqAg0QgIgJgDgJQgCgKAFgPQACgHADgEQAGgJAKgFQALgGALABIAAgCQAMABAKAHQALAHAFALQAGALgBANQgBAMgGALQgLARgTACIgFABQgUAAgQgSgEg13AeDQgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAGgGQAUgUAPAGIAAgEQAYADAMAUQANAUgJAWQgIATgRAGQgHADgIAAQgJAAgKgFgEgy5AeCQgMgGgIgLQgHgJAAgIIABgOIACgLQACgEAGgHQAUgTAPAGIAAgFQAVAHAIAIQAJAIADAMQADALgCAMQgDANgKALQgKAKgNACIgEAAQgLAAgKgGgEgxvAcCQgIgGgGgKQgIgKAAgHQgBgDADgKIACgMQACgFAFgFQATgTAQAFIAAgDQAQABAMAMQAMALACAPQADANgFAMQgFANgKAHQgLAIgNAAQgOAAgLgHgEhtcAbKQgLgBgJgGQgHgFgIgLQgIgKAAgIIACgMIACgMQACgFAGgFQASgUARAGIAAgEQASAEAKAKQAJAIAEAMQAEAMgDALQgFAXgUAKQgIADgJAAIgEAAgEhkeAYJQgMgFgJgKQgHgIgDgKQgCgJAFgQIAFgKQAGgKAKgFQALgFALABIAAgCQANABALAIQALAJAFAMQAFANgDANQgDANgJAKQgIAKgLADIgJABQgIAAgJgEgEgvBAYFQgHgFgIgLQgIgKAAgHQAAgDACgKIACgLQACgFAGgGQATgTAQAFIAAgDQANABALAJQALAIAFAMQAFANgDAPQgDAOgLAKQgKAJgPABIgCAAQgOAAgLgHgEhnAAXdQgNgBgOgMQgMgLgEgMQgCgLAFgOIAFgLQAGgJAKgFQALgFALABIAAgDQAMABAKAHQALAHAFALQAFALAAANQgBAMgGAKQgGAKgKAGQgJAFgKAAIgEAAgEhrRAXWQgIgFgHgKQgHgJgBgHQgBgGACgJQAAgGADgGIAIgLQASgSAQAFIAAgFQAUAFAMANQAGAIADAJQAEANgEAOQgEAOgKAIQgKAJgPAAIgDAAQgMAAgKgGgEhmBAVKQgKgFgLgPQgHgKAAgGIACgNIACgLQABgEAHgGQATgUAQAGIAAgEQAXADANAUQANAVgKAWQgHARgRAHQgIAEgIAAQgJAAgJgGgEhERAUOQgUgEgMgUQgFgJgBgHIACgMIACgLQABgEAHgIQASgSARAFIAAgEQAMACALAIQAKAHAFALQAGAMgBANQgBANgIAKQgHAKgMAFQgHADgHAAIgKgCgEhJsAT4QgFgDgKgMQgIgLAAgHIACgNIACgLQACgFAGgGQATgTAQAGIAAgEQANACAMAJQALAJAEAMQAFAOgEAOQgDAOgLAJQgKAJgPAAIgDAAQgNAAgKgHgEhuLATMQgKgGgKgPQgHgJAAgHIACgMIACgLQABgEAGgHQAUgTAPAFIAAgDQAYACAMAUQANAVgJAWQgIASgRAHQgHADgIAAQgJAAgKgFgEhj1ASrQgJgGgKgNQgGgKAAgGIACgNIACgLQACgFAGgGQASgSAQAFIAAgEQAOACALAIQALAJAFAMQAEAOgDANQgDAOgKAJQgKAKgOABIgFABQgMAAgJgGgA0eSNQgPgGgKgQQgFgJAAgHIACgMIACgLQABgEAHgHQATgTAPAGIAAgEQAVAHAIAHQAJAIAEAMQADAMgDAMQgGAYgTAIQgHADgIAAQgJAAgJgEgEBtqASMQgOgGgJgNQgFgJgBgIIACgNIACgLQACgEAGgHQASgSARAFIAAgEQAVAHAIAHQAJAIADAMQADAMgCAMQgDANgJAJQgIAJgMADIgJABQgJAAgKgFgEhjUAP+QgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAHgGQATgUAQAGIAAgEQAYADAMAUQANAUgKAWQgHATgRAGQgIADgHAAQgKAAgKgFgA2QPhQgHgIgDgKQgDgJAFgQQADgHACgDQAGgKALgFQAKgFALABIAAgDQAMABALAIQAKAHAFALQAGALgBAMQAAANgHAKQgKARgUADIgFAAQgTAAgRgSgAzNPwQgMgFgJgKQgJgKgBgIQgDgKAFgPIAFgLQAGgJALgFQAKgFALABIAAgDQANABALAJQALAIAFAMQAFANgCANQgDANgJAKQgJAKgKADIgKABQgHAAgJgDgEBqQAPQQgMgFgJgKQgIgJgCgJQgDgJAFgPIAFgLQAGgJALgGQAKgFALABIAAgCQANABAMAIQALAJAEANQAFAMgDAOQgCAOgKAJQgIAJgMADIgIABQgIAAgIgEgEhAgAMwQgKgGgJgNQgHgKAAgHIACgMIACgMQACgFAGgFQASgTARAFIAAgDQANABALAJQALAJAFAMQAFANgDAOQgEAOgJAJQgKAJgPACIgGAAQgKAAgJgFgEhBvALBQgKgGgJgNQgHgKAAgGIACgNIACgLQACgFAGgGQASgTARAGIAAgDQAWABAMASQANARgFAWQgGAVgTAJQgJAEgJAAQgKAAgKgGgEA3RAHjQgLgGgIgMQgGgKAAgHIACgNIACgLQACgFAFgFQATgTAQAFIAAgDQAMABALAHQALAIAFALQAFAMgBANQgBANgIAKQgLAPgSADIgDAAQgMAAgLgHgEhCOAHkQgLgHgIgLQgHgJAAgIIABgNIACgLQACgFAGgGQATgTAQAFIAAgDQAMABAKAHQALAIAFALQAGALgBAMQgBANgHAKQgLASgTABIgEABQgKAAgLgGgEA0sAHfQgPgFgKgNQgKgNAAgQQAAgKAFgLQAGgNALgIQAMgJANADIAAgDQAQACAMALQAMALADAPQAEAQgGAPQgHAPgNAJQgJAHgLAAQgGAAgHgDgEhABAGlQgJgGgJgNQgHgKAAgHIACgMIACgMQACgFAFgFQATgTAQAFIAAgDQAWACANASQAMASgFAWQgGAUgTAJQgJAEgIAAQgLAAgKgGgEA2iAFGQgJgGgKgNQgHgKAAgHIACgMIACgMQACgEAGgHQATgSAQAFIAAgDQANABALAJQALAJAFAMQAFANgDAOQgEAOgJAJQgKAJgPACIgGAAQgKAAgJgFgEA3eADVQgFgEgKgMQgIgMAAgFIACgNIACgLQACgFAGgGQATgTAQAGIAAgEQANABALAJQALAJAFAMQAFANgDAPQgEAOgKAJQgLAJgPABIgBAAQgOAAgLgHgEAupADIQgKgGgKgOQgHgKAAgGIACgNIACgKQABgFAHgGQATgUAQAGIAAgEQAYADAMAUQANAUgKAWQgGASgSAHQgIADgHAAQgKAAgKgFgEA67ACdQgSgEgOgUQgGgKAAgHIACgMIACgLQACgGAGgFQASgUAQAGIAAgDQAPABAMALQAMALADAOQAGAXgQASQgHAJgLADQgHADgHAAIgIgBgAaYCYQgKgGgIgMQgHgJgBgIIACgNIACgLQACgFAGgHQASgSARAFIAAgDQANABALAJQALAJAFAMQAFANgDAOQgEAOgJAJQgKAJgOACIgGAAQgLAAgJgFgAXbB/QgOgCgLgLQgKgKgEgNQgDgJAAgGQABgSAOgMQANgMASACIAAgDQANgBANAHQAMAGAHAMQAGALAAAOQgBAOgHALQgIALgNAGQgJAEgIAAIgJgBgAbNgTQgPgFgKgQQgGgJAAgIIACgMIACgMQADgGAFgEQARgTARAFIAAgEQAVAHAIAHQAJAIADANQAEAMgDAMQgFAXgTAIQgIAEgIAAQgIAAgJgEgEA6/gAkQgJgGgKgOQgHgKAAgGIACgNIACgLQACgFAFgGQATgSAQAFIAAgDQAYABANAWQAMAUgKAXQgIARgRAHQgHACgHAAQgLAAgJgFgEA2AgBGQgOgIgHgRQgGgRAFgQQAFgPAMgJQAOgKAOACIAAgDQAPABAMALQAMALADAPQACAJgBAMQgBAMgGAJQgJAOgSAEIgKABQgMAAgKgGgAYKhVQgMgGgIgMQgGgKAAgHIACgNIACgLQACgFAGgFQATgTAPAFIAAgDQANABAKAHQAKAIAGALQAFALgBANQgBANgHAKQgMARgRABIgEABQgLAAgLgHgEA3mgEQQgPgHgKgOQgFgJgBgIIACgMIACgLQACgFAGgGQATgTAQAGIAAgFQAWAIAGAGQAJAHAEANQADALgCAMQgFAagWAIQgGADgHAAQgIAAgKgEgEA1vgFkQgGgEgJgMQgHgKAAgGIACgNIACgLQACgFAFgGQASgTARAGIAAgFQATAGAKAIQAKAKADAPQAEAOgGANQgIAUgTAFQgHADgHAAQgMAAgLgJgEAhDgMrQgJgFgKgOQgHgKAAgHIACgMIACgMQACgFAFgFQAUgTAPAFIAAgDQAWACAMARQANASgFAVQgFAVgSAJQgKAFgJAAQgKAAgKgGgEAiugO8QgHgEgIgMQgHgKAAgHQgBgDADgJIACgMQACgFAGgGQAJgJAJgDQAQAFASACIAJAAQAJAIAEALQAFAOgDAOQgEAOgKAJQgLAKgPABIgBAAQgPAAgKgIgAf2ySQgMAAgJgHQgIgFgGgJQgHgJgBgHQgBgHACgKQABgHADgEQAFgMALgHQAMgHANACIAAgEQARAEALAKQARAQgCAXQgDAZgVALQgJAEgJAAIgEAAgEAzngbPQgOgHgJgOQgGgKAAgGIACgMIACgLQACgFAGgGQATgTAQAFIAAgEQAWAIAGAGQAJAHAEANQADALgCANQgDAMgIAJQgIAKgMADIgJACQgKAAgKgFgEA0ygcAQgHgFgHgJQgIgKgCgGQgBgHACgLQABgFADgHQAFgLAMgHQALgHANACIAAgDQANABALAIQALAJAFAMQAFANgDAOQgDAOgKAKQgKAJgPACIgEAAQgMAAgKgGgEBD0ge/QgHgFgHgLQgHgKgBgGQgBgEACgJIADgNQADgFAFgGQASgSAQAFIAAgDQAOACALAJQALAJAFAMQAEAOgDAOQgEAOgLAJQgKAIgPABIgBAAQgOAAgLgHgEA7+gfMQgJgFgKgPQgHgKAAgGIACgNIACgLQACgFAFgGQAUgSAPAFIAAgEQAWADAMARQANARgFAVQgFAVgSAKQgKAEgJAAQgKAAgKgFgEAROggsQgJgGgJgOQgHgIAAgHIACgMIACgLQACgFAGgHQATgTAQAGIAAgEQANACALAIQALAJAFANQAFANgDANQgEAOgJAKQgKAJgPABIgFABQgLAAgKgGgEAQQgjKQgMgHgHgMQgGgIgBgIIACgNIACgLQACgFAGgGQASgSAQAFIAAgEQAMABALAIQALAHAFALQAFALgBANQAAANgHAKQgMARgTACIgEAAQgKAAgLgGgEASWglVQgMgEgJgKQgJgJgCgJQgDgMAFgPIAFgKQAGgKAKgFQALgFALABIAAgDQAVAHAJAIQAIAHADAMQADALgCALQgCANgIAJQgIAKgLAEQgFABgGAAQgHAAgIgCg");
	this.shape.setTransform(719.0068,-20.6819);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#5B075F").s().p("Eg5vAmuQgMgFgJgLQgIgJgCgIQgCgLAEgOIAFgKQAGgKALgFQAKgFALABIAAgDQAVAHAIAHQAJAHADANQAEALgDAMQgCAMgIAKQgIAJgMAEIgJABQgIAAgJgDgEg1sAi8QgHgFgHgKQgIgJAAgIQgBgDADgKIACgMQACgFAGgGQASgSAQAFIAAgEQAOACALAJQAMAJAEANQAEANgDAPQgEAOgLAIQgLAJgOAAIgCAAQgOAAgKgHgEgz9Ah9QgFgDgKgMQgIgLAAgHIACgNIACgLQACgFAGgGQATgTAQAGIAAgEQANACAMAJQALAJAEAMQAFAOgEAOQgDAOgLAJQgKAJgPAAIgDAAQgNAAgKgHgEg13AeDQgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAGgGQAUgUAPAGIAAgEQAYADAMAUQANAUgJAWQgIATgRAGQgHADgIAAQgJAAgKgFgEgy5AeCQgMgGgIgLQgHgJAAgIIABgOIACgLQACgEAGgHQAUgTAPAGIAAgFQAVAHAIAIQAJAIADAMQADALgCAMQgDANgKALQgKAKgNACIgEAAQgLAAgKgGgEgxvAcCQgIgGgGgKQgIgKAAgHQgBgDADgKIACgMQACgFAFgFQATgTAQAFIAAgDQAQABAMAMQAMALACAPQADANgFAMQgFANgKAHQgLAIgNAAQgOAAgLgHgEgvBAYFQgHgFgIgLQgIgKAAgHQAAgDACgKIACgLQACgFAGgGQATgTAQAFIAAgDQANABALAJQALAIAFAMQAFANgDAPQgDAOgLAKQgKAJgPABIgCAAQgOAAgLgHgEhrRAXWQgIgFgHgKQgHgJgBgHQgBgGACgJQAAgGADgGIAIgLQASgSAQAFIAAgFQAUAFAMANQAGAIADAJQAEANgEAOQgEAOgKAIQgKAJgPAAIgDAAQgMAAgKgGgEhnoAWgIAFgLQAGgJAKgFQALgFALABIAAgDQAMABAKAHQgNAEgNAHQgaAOgQAVQgBgKAEgMgEhmBAVKQgKgFgLgPQgHgKAAgGIACgNIACgLQABgEAHgGQATgUAQAGIAAgEQAXADANAUQANAVgKAWQgHARgRAHQgIAEgIAAQgJAAgJgGgEhJsAT4QgFgDgKgMQgIgLAAgHIACgNIACgLQACgFAGgGQATgTAQAGIAAgEQANACAMAJQALAJAEAMQAFAOgEAOQgDAOgLAJQgKAJgPAAIgDAAQgNAAgKgHgEhuLATMQgKgGgKgPQgHgJAAgHIACgMIACgLQABgEAGgHQAUgTAPAFIAAgDQAYACAMAUQANAVgJAWQgIASgRAHQgHADgIAAQgJAAgKgFgEhj1ASrQgJgGgKgNQgGgKAAgGIACgNIACgLQACgFAGgGQASgSAQAFIAAgEQAOACALAIQALAJAFAMQAEAOgDANQgDAOgKAJQgKAKgOABIgFABQgMAAgJgGgEBtqASMQgOgGgJgNQgFgJgBgIIACgNIACgLQACgEAGgHQASgSARAFIAAgEQAVAHAIAHQAJAIADAMQADAMgCAMQgDANgJAJQgIAJgMADIgJABQgJAAgKgFgEhjUAP+QgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAHgGQATgUAQAGIAAgEQAYADAMAUQANAUgKAWQgHATgRAGQgIADgHAAQgKAAgKgFgA2QPhQgHgIgDgKQgDgJAFgQQADgHACgDQAGgKALgFQAKgFALABIAAgDQAMABALAIQAKAHAFALQAGALgBAMQAAANgHAKQgKARgUADIgFAAQgTAAgRgSgAzNPwQgMgFgJgKQgJgKgBgIQgDgKAFgPIAFgLQAGgJALgFQAKgFALABIAAgDQANABALAJQALAIAFAMQAFANgCANQgDANgJAKQgJAKgKADIgKABQgHAAgJgDgEBqQAPQQgMgFgJgKQgIgJgCgJQgDgJAFgPIAFgLQAGgJALgGQAKgFALABIAAgCQANABAMAIQALAJAEANQAFAMgDAOQgCAOgKAJQgIAJgMADIgIABQgIAAgIgEgEhCJAKeIACgNIACgLQACgFAGgGQASgTARAGIAAgDQAMABAJAFIgGACQgmAOgYAeIAAgBgEA3RAHjQgLgGgIgMQgGgKAAgHIACgNIACgLQACgFAFgFQATgTAQAFIAAgDQAMABALAHQALAIAFALQAFAMgBANQgBANgIAKQgLAPgSADIgDAAQgMAAgLgHgEhCOAHkQgLgHgIgLQgHgJAAgIIABgNIACgLQACgFAGgGQATgTAQAFIAAgDQAMABAKAHQALAIAFALQAGALgBAMQgBANgHAKQgLASgTABIgEABQgKAAgLgGgEA0sAHfQgPgFgKgNQgKgNAAgQQAAgKAFgLQAGgNALgIQAMgJANADIAAgDQAQACAMALQAMALADAPQAEAQgGAPQgHAPgNAJQgJAHgLAAQgGAAgHgDgEhABAGlQgJgGgJgNQgHgKAAgHIACgMIACgMQACgFAFgFQATgTAQAFIAAgDQAWACANASQAMASgFAWQgGAUgTAJQgJAEgIAAQgLAAgKgGgEA2iAFGQgJgGgKgNQgHgKAAgHIACgMIACgMQACgEAGgHQATgSAQAFIAAgDQANABALAJQALAJAFAMQAFANgDAOQgEAOgJAJQgKAJgPACIgGAAQgKAAgJgFgEA3eADVQgFgEgKgMQgIgMAAgFIACgNIACgLQACgFAGgGQATgTAQAGIAAgEQANABALAJQALAJAFAMQAFANgDAPQgEAOgKAJQgLAJgPABIgBAAQgOAAgLgHgEAupADIQgKgGgKgOQgHgKAAgGIACgNIACgKQABgFAHgGQATgUAQAGIAAgEQAYADAMAUQANAUgKAWQgGASgSAHQgIADgHAAQgKAAgKgFgEA67ACdQgSgEgOgUQgGgKAAgHIACgMIACgLQACgGAGgFQASgUAQAGIAAgDQAPABAMALQAMALADAOQAGAXgQASQgHAJgLADQgHADgHAAIgIgBgAaYCYQgKgGgIgMQgHgJgBgIIACgNIACgLQACgFAGgHQASgSARAFIAAgDQANABALAJQALAJAFAMQAFANgDAOQgEAOgJAJQgKAJgOACIgGAAQgLAAgJgFgAXbB/QgOgCgLgLQgKgKgEgNQgDgJAAgGQABgSAOgMQANgMASACIAAgDQANgBANAHQAMAGAHAMQAGALAAAOQgBAOgHALQgIALgNAGQgJAEgIAAIgJgBgAbNgTQgPgFgKgQQgGgJAAgIIACgMIACgMQADgGAFgEQARgTARAFIAAgEQAVAHAIAHQAJAIADANQAEAMgDAMQgFAXgTAIQgIAEgIAAQgIAAgJgEgEA6/gAkQgJgGgKgOQgHgKAAgGIACgNIACgLQACgFAFgGQATgSAQAFIAAgDQAYABANAWQAMAUgKAXQgIARgRAHQgHACgHAAQgLAAgJgFgEA2AgBGQgOgIgHgRQgGgRAFgQQAFgPAMgJQAOgKAOACIAAgDQAPABAMALQAMALADAPQACAJgBAMQgBAMgGAJQgJAOgSAEIgKABQgMAAgKgGgAYKhVQgMgGgIgMQgGgKAAgHIACgNIACgLQACgFAGgFQATgTAPAFIAAgDQANABAKAHQAKAIAGALQAFALgBANQgBANgHAKQgMARgRABIgEABQgLAAgLgHgEA3mgEQQgPgHgKgOQgFgJgBgIIACgMIACgLQACgFAGgGQATgTAQAGIAAgFQAWAIAGAGQAJAHAEANQADALgCAMQgFAagWAIQgGADgHAAQgIAAgKgEgEA1vgFkQgGgEgJgMQgHgKAAgGIACgNIACgLQACgFAFgGQASgTARAGIAAgFQATAGAKAIQAKAKADAPQAEAOgGANQgIAUgTAFQgHADgHAAQgMAAgLgJgEAhDgMrQgJgFgKgOQgHgKAAgHIACgMIACgMQACgFAFgFQAUgTAPAFIAAgDQAWACAMARQANASgFAVQgFAVgSAJQgKAFgJAAQgKAAgKgGgEAiugO8QgHgEgIgMQgHgKAAgHQgBgDADgJIACgMQACgFAGgGQAJgJAJgDQAQAFASACIAJAAQAJAIAEALQAFAOgDAOQgEAOgKAJQgLAKgPABIgBAAQgPAAgKgIgAf2ySQgMAAgJgHQgIgFgGgJQgHgJgBgHQgBgHACgKQABgHADgEQAFgMALgHQAMgHANACIAAgEQARAEALAKQARAQgCAXQgDAZgVALQgJAEgJAAIgEAAgEAzngbPQgOgHgJgOQgGgKAAgGIACgMIACgLQACgFAGgGQATgTAQAFIAAgEQAWAIAGAGQAJAHAEANQADALgCANQgDAMgIAJQgIAKgMADIgJACQgKAAgKgFgEA0ygcAQgHgFgHgJQgIgKgCgGQgBgHACgLQABgFADgHQAFgLAMgHQALgHANACIAAgDQANABALAIQALAJAFAMQAFANgDAOQgDAOgKAKQgKAJgPACIgEAAQgMAAgKgGgEBD0ge/QgHgFgHgLQgHgKgBgGQgBgEACgJIADgNQADgFAFgGQASgSAQAFIAAgDQAOACALAJQALAJAFAMQAEAOgDAOQgEAOgLAJQgKAIgPABIgBAAQgOAAgLgHgEA7+gfMQgJgFgKgPQgHgKAAgGIACgNIACgLQACgFAFgGQAUgSAPAFIAAgEQAWADAMARQANARgFAVQgFAVgSAKQgKAEgJAAQgKAAgKgFgEAROggsQgJgGgJgOQgHgIAAgHIACgMIACgLQACgFAGgHQATgTAQAGIAAgEQANACALAIQALAJAFANQAFANgDANQgEAOgJAKQgKAJgPABIgFABQgLAAgKgGgEAQQgjKQgMgHgHgMQgGgIgBgIIACgNIACgLQACgFAGgGQASgSAQAFIAAgEQAMABALAIQALAHAFALQAFALgBANQAAANgHAKQgMARgTACIgEAAQgKAAgLgGgEASWglVQgMgEgJgKQgJgJgCgJQgDgMAFgPIAFgKQAGgKAKgFQALgFALABIAAgDQAVAHAJAIQAIAHADAMQADALgCALQgCANgIAJQgIAKgLAEQgFABgGAAQgHAAgIgCg");
	this.shape_1.setTransform(719.0068,-20.6819);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#5B075F").s().p("Eg5vAmuQgMgFgJgLQgIgJgCgIQgCgLAEgOIAFgKQAGgKALgFQAKgFALABIAAgDQAVAHAIAHQAJAHADANQAEALgDAMQgCAMgIAKQgIAJgMAEIgJABQgIAAgJgDgEg1sAi8QgHgFgHgKQgIgJAAgIQgBgDADgKIACgMQACgFAGgGQASgSAQAFIAAgEQAOACALAJQAMAJAEANQAEANgDAPQgEAOgLAIQgLAJgOAAIgCAAQgOAAgKgHgEgz9Ah9QgFgDgKgMQgIgLAAgHIACgNIACgLQACgFAGgGQATgTAQAGIAAgEQANACAMAJQALAJAEAMQAFAOgEAOQgDAOgLAJQgKAJgPAAIgDAAQgNAAgKgHgEg13AeDQgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAGgGQAUgUAPAGIAAgEQAYADAMAUQANAUgJAWQgIATgRAGQgHADgIAAQgJAAgKgFgEgy5AeCQgMgGgIgLQgHgJAAgIIABgOIACgLQACgEAGgHQAUgTAPAGIAAgFQAVAHAIAIQAJAIADAMQADALgCAMQgDANgKALQgKAKgNACIgEAAQgLAAgKgGgEgxvAcCQgIgGgGgKQgIgKAAgHQgBgDADgKIACgMQACgFAFgFQATgTAQAFIAAgDQAQABAMAMQAMALACAPQADANgFAMQgFANgKAHQgLAIgNAAQgOAAgLgHgEgvBAYFQgHgFgIgLQgIgKAAgHQAAgDACgKIACgLQACgFAGgGQATgTAQAFIAAgDQANABALAJQALAIAFAMQAFANgDAPQgDAOgLAKQgKAJgPABIgCAAQgOAAgLgHgEhrRAXWQgIgFgHgKQgHgJgBgHQgBgGACgJQAAgGADgGIAIgLQASgSAQAFIAAgFQAUAFAMANQAGAIADAJQAEANgEAOQgEAOgKAIQgKAJgPAAIgDAAQgMAAgKgGgEhnoAWgIAFgLQAGgJAKgFQALgFALABIAAgDQAMABAKAHQgNAEgNAHQgaAOgQAVQgBgKAEgMgEhmBAVKQgKgFgLgPQgHgKAAgGIACgNIACgLQABgEAHgGQATgUAQAGIAAgEQAXADANAUQANAVgKAWQgHARgRAHQgIAEgIAAQgJAAgJgGgEhuLATMQgKgGgKgPQgHgJAAgHIACgMIACgLQABgEAGgHQAUgTAPAFIAAgDQAYACAMAUQANAVgJAWQgIASgRAHQgHADgIAAQgJAAgKgFgEhj1ASrQgJgGgKgNQgGgKAAgGIACgNIACgLQACgFAGgGQASgSAQAFIAAgEQAOACALAIQALAJAFAMQAEAOgDANQgDAOgKAJQgKAKgOABIgFABQgMAAgJgGgEBtqASMQgOgGgJgNQgFgJgBgIIACgNIACgLQACgEAGgHQASgSARAFIAAgEQAVAHAIAHQAJAIADAMQADAMgCAMQgDANgJAJQgIAJgMADIgJABQgJAAgKgFgEhjUAP+QgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAHgGQATgUAQAGIAAgEQAYADAMAUQANAUgKAWQgHATgRAGQgIADgHAAQgKAAgKgFgA2QPhQgHgIgDgKQgDgJAFgQQADgHACgDQAGgKALgFQAKgFALABIAAgDQAMABALAIQAKAHAFALQAGALgBAMQAAANgHAKQgKARgUADIgFAAQgTAAgRgSgAzNPwQgMgFgJgKQgJgKgBgIQgDgKAFgPIAFgLQAGgJALgFQAKgFALABIAAgDQANABALAJQALAIAFAMQAFANgCANQgDANgJAKQgJAKgKADIgKABQgHAAgJgDgEBqQAPQQgMgFgJgKQgIgJgCgJQgDgJAFgPIAFgLQAGgJALgGQAKgFALABIAAgCQANABAMAIQALAJAEANQAFAMgDAOQgCAOgKAJQgIAJgMADIgIABQgIAAgIgEgEhCJAKeIACgNIACgLQACgFAGgGQASgTARAGIAAgDQAMABAJAFIgGACQgmAOgYAeIAAgBgEhCOAHkQgLgHgIgLQgHgJAAgIIABgNIACgLQACgFAGgGQATgTAQAFIAAgDQAMABAKAHQALAIAFALQAGALgBAMQgBANgHAKQgLASgTABIgEABQgKAAgLgGgEhABAGlQgJgGgJgNQgHgKAAgHIACgMIACgMQACgFAFgFQATgTAQAFIAAgDQAWACANASQAMASgFAWQgGAUgTAJQgJAEgIAAQgLAAgKgGgEA3eADVQgFgEgKgMQgIgMAAgFIACgNIACgLQACgFAGgGQATgTAQAGIAAgEQANABALAJQALAJAFAMQAFANgDAPQgEAOgKAJQgLAJgPABIgBAAQgOAAgLgHgEA67ACdQgSgEgOgUQgGgKAAgHIACgMIACgLQACgGAGgFQASgUAQAGIAAgDQAPABAMALQAMALADAOQAGAXgQASQgHAJgLADQgHADgHAAIgIgBgAaYCYQgKgGgIgMQgHgJgBgIIACgNIACgLQACgFAGgHQASgSARAFIAAgDQANABALAJQALAJAFAMQAFANgDAOQgEAOgJAJQgKAJgOACIgGAAQgLAAgJgFgAXbB/QgOgCgLgLQgKgKgEgNQgDgJAAgGQABgSAOgMQANgMASACIAAgDQANgBANAHQAMAGAHAMQAGALAAAOQgBAOgHALQgIALgNAGQgJAEgIAAIgJgBgAbNgTQgPgFgKgQQgGgJAAgIIACgMIACgMQADgGAFgEQARgTARAFIAAgEQAVAHAIAHQAJAIADANQAEAMgDAMQgFAXgTAIQgIAEgIAAQgIAAgJgEgEA6/gAkQgJgGgKgOQgHgKAAgGIACgNIACgLQACgFAFgGQATgSAQAFIAAgDQAYABANAWQAMAUgKAXQgIARgRAHQgHACgHAAQgLAAgJgFgEA2AgBGQgOgIgHgRQgGgRAFgQQAFgPAMgJQAOgKAOACIAAgDQAPABAMALQAMALADAPQACAJgBAMQgBAMgGAJQgJAOgSAEIgKABQgMAAgKgGgAYKhVQgMgGgIgMQgGgKAAgHIACgNIACgLQACgFAGgFQATgTAPAFIAAgDQANABAKAHQAKAIAGALQAFALgBANQgBANgHAKQgMARgRABIgEABQgLAAgLgHgEA3mgEQQgPgHgKgOQgFgJgBgIIACgMIACgLQACgFAGgGQATgTAQAGIAAgFQAWAIAGAGQAJAHAEANQADALgCAMQgFAagWAIQgGADgHAAQgIAAgKgEgEA1vgFkQgGgEgJgMQgHgKAAgGIACgNIACgLQACgFAFgGQASgTARAGIAAgFQATAGAKAIQAKAKADAPQAEAOgGANQgIAUgTAFQgHADgHAAQgMAAgLgJgEAhDgMrQgJgFgKgOQgHgKAAgHIACgMIACgMQACgFAFgFQAUgTAPAFIAAgDQAWACAMARQANASgFAVQgFAVgSAJQgKAFgJAAQgKAAgKgGgEAiugO8QgHgEgIgMQgHgKAAgHQgBgDADgJIACgMQACgFAGgGQAJgJAJgDQAQAFASACIAJAAQAJAIAEALQAFAOgDAOQgEAOgKAJQgLAKgPABIgBAAQgPAAgKgIgAf2ySQgMAAgJgHQgIgFgGgJQgHgJgBgHQgBgHACgKQABgHADgEQAFgMALgHQAMgHANACIAAgEQARAEALAKQARAQgCAXQgDAZgVALQgJAEgJAAIgEAAgEAzngbPQgOgHgJgOQgGgKAAgGIACgMIACgLQACgFAGgGQATgTAQAFIAAgEQAWAIAGAGQAJAHAEANQADALgCANQgDAMgIAJQgIAKgMADIgJACQgKAAgKgFgEA0ygcAQgHgFgHgJQgIgKgCgGQgBgHACgLQABgFADgHQAFgLAMgHQALgHANACIAAgDQANABALAIQALAJAFAMQAFANgDAOQgDAOgKAKQgKAJgPACIgEAAQgMAAgKgGgEBD0ge/QgHgFgHgLQgHgKgBgGQgBgEACgJIADgNQADgFAFgGQASgSAQAFIAAgDQAOACALAJQALAJAFAMQAEAOgDAOQgEAOgLAJQgKAIgPABIgBAAQgOAAgLgHgEA7+gfMQgJgFgKgPQgHgKAAgGIACgNIACgLQACgFAFgGQAUgSAPAFIAAgEQAWADAMARQANARgFAVQgFAVgSAKQgKAEgJAAQgKAAgKgFgEAROggsQgJgGgJgOQgHgIAAgHIACgMIACgLQACgFAGgHQATgTAQAGIAAgEQANACALAIQALAJAFANQAFANgDANQgEAOgJAKQgKAJgPABIgFABQgLAAgKgGgEAQQgjKQgMgHgHgMQgGgIgBgIIACgNIACgLQACgFAGgGQASgSAQAFIAAgEQAMABALAIQALAHAFALQAFALgBANQAAANgHAKQgMARgTACIgEAAQgKAAgLgGgEASWglVQgMgEgJgKQgJgJgCgJQgDgMAFgPIAFgKQAGgKAKgFQALgFALABIAAgDQAVAHAJAIQAIAHADAMQADALgCALQgCANgIAJQgIAKgLAEQgFABgGAAQgHAAgIgCg");
	this.shape_2.setTransform(719.0068,-20.6819);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#5B075F").s().p("Eg5vAmuQgMgFgJgLQgIgJgCgIQgCgLAEgOIAFgKQAGgKALgFQAKgFALABIAAgDQAVAHAIAHQAJAHADANQAEALgDAMQgCAMgIAKQgIAJgMAEIgJABQgIAAgJgDgEg1sAi8QgHgFgHgKQgIgJAAgIQgBgDADgKIACgMQACgFAGgGQASgSAQAFIAAgEQAOACALAJQAMAJAEANQAEANgDAPQgEAOgLAIQgLAJgOAAIgCAAQgOAAgKgHgEgz9Ah9QgFgDgKgMQgIgLAAgHIACgNIACgLQACgFAGgGQATgTAQAGIAAgEQANACAMAJQALAJAEAMQAFAOgEAOQgDAOgLAJQgKAJgPAAIgDAAQgNAAgKgHgEg13AeDQgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAGgGQAUgUAPAGIAAgEQAYADAMAUQANAUgJAWQgIATgRAGQgHADgIAAQgJAAgKgFgEgy5AeCQgMgGgIgLQgHgJAAgIIABgOIACgLQACgEAGgHQAUgTAPAGIAAgFQAVAHAIAIQAJAIADAMQADALgCAMQgDANgKALQgKAKgNACIgEAAQgLAAgKgGgEgxvAcCQgIgGgGgKQgIgKAAgHQgBgDADgKIACgMQACgFAFgFQATgTAQAFIAAgDQAQABAMAMQAMALACAPQADANgFAMQgFANgKAHQgLAIgNAAQgOAAgLgHgEgvBAYFQgHgFgIgLQgIgKAAgHQAAgDACgKIACgLQACgFAGgGQATgTAQAFIAAgDQANABALAJQALAIAFAMQAFANgDAPQgDAOgLAKQgKAJgPABIgCAAQgOAAgLgHgEhrRAXWQgIgFgHgKQgHgJgBgHQgBgGACgJQAAgGADgGIAIgLQASgSAQAFIAAgFQAUAFAMANQAGAIADAJQAEANgEAOQgEAOgKAIQgKAJgPAAIgDAAQgMAAgKgGgEhnoAWgIAFgLIACgCIAAAAIANAMQgNAKgKANQgBgKAEgMgEhkDATzQgMgGgDgIIgCgNIgCgKQgBgEADgGQAFgMAJgGQAMgHAKADIAAgEQAYAIAGAJQAIAMgDATQgEATgMAHQgHAEgJAAQgJAAgNgFgEhuLATMQgKgGgKgPQgHgJAAgHIACgMIACgLQABgEAGgHQAUgTAPAFIAAgDQAYACAMAUQANAVgJAWQgIASgRAHQgHADgIAAQgJAAgKgFgEBtqASMQgOgGgJgNQgFgJgBgIIACgNIACgLQACgEAGgHQASgSARAFIAAgEQAVAHAIAHQAJAIADAMQADAMgCAMQgDANgJAJQgIAJgMADIgJABQgJAAgKgFgEhjUAP+QgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAHgGQATgUAQAGIAAgEQAYADAMAUQANAUgKAWQgHATgRAGQgIADgHAAQgKAAgKgFgEBqQAPQQgMgFgJgKQgIgJgCgJQgDgJAFgPIAFgLQAGgJALgGQAKgFALABIAAgCQANABAMAIQALAJAEANQAFAMgDAOQgCAOgKAJQgIAJgMADIgIABQgIAAgIgEgA2COdQAKgFALABIAAgDIAKACIgBAAQgTADgQAFIAFgDgEg/YAFUIgUgEIAAgCQAMABAJAGIgBgBgEA3eADVQgFgEgKgMQgIgMAAgFIACgNIACgLQACgFAGgGQATgTAQAGIAAgEQANABALAJQALAJAFAMQAFANgDAPQgEAOgKAJQgLAJgPABIgBAAQgOAAgLgHgEBHYACmQgPgCgNgKQgEgFgBgCQgBgEAAgGIgDgLQAAgIAEgIQAFgJAJgHQALgGAKAEIAAgFQAYAJAHAMQAHANgFATQgCAJgGAGQgJALgPAAIgDAAgEA67ACdQgSgEgOgUQgGgKAAgHIACgMIACgLQACgGAGgFQASgUAQAGIAAgDQAPABAMALQAMALADAOQAGAXgQASQgHAJgLADQgHADgHAAIgIgBgAaYCYQgKgGgIgMQgHgJgBgIIACgNIACgLQACgFAGgHQASgSARAFIAAgDQANABALAJQALAJAFAMQAFANgDAOQgEAOgJAJQgKAJgOACIgGAAQgLAAgJgFgAXbB/QgOgCgLgLQgKgKgEgNQgDgJAAgGQABgSAOgMQANgMASACIAAgDQANgBANAHQAMAGAHAMQAGALAAAOQgBAOgHALQgIALgNAGQgJAEgIAAIgJgBgAbNgTQgPgFgKgQQgGgJAAgIIACgMIACgMQADgGAFgEQARgTARAFIAAgEQAVAHAIAHQAJAIADANQAEAMgDAMQgFAXgTAIQgIAEgIAAQgIAAgJgEgEA6/gAkQgJgGgKgOQgHgKAAgGIACgNIACgLQACgFAFgGQATgSAQAFIAAgDQAYABANAWQAMAUgKAXQgIARgRAHQgHACgHAAQgLAAgJgFgEA2AgBGQgOgIgHgRQgGgRAFgQQAFgPAMgJQAOgKAOACIAAgDQAPABAMALQAMALADAPQACAJgBAMQgBAMgGAJQgJAOgSAEIgKABQgMAAgKgGgAYKhVQgMgGgIgMQgGgKAAgHIACgNIACgLQACgFAGgFQATgTAPAFIAAgDQANABAKAHQAKAIAGALQAFALgBANQgBANgHAKQgMARgRABIgEABQgLAAgLgHgEBHbgBzIgFgGQgBgDABgHIgDgLQgBgGAEgKQAGgKAJgFQAJgGALADIAAgEQAZAIAHANQAHAMgGAUQgEALgEAEQgHAIgKABIgGABQgQAAgQgNgEA3mgEQQgPgHgKgOQgFgJgBgIIACgMIACgLQACgFAGgGQATgTAQAGIAAgFQAWAIAGAGQAJAHAEANQADALgCAMQgFAagWAIQgGADgHAAQgIAAgKgEgEA1vgFkQgGgEgJgMQgHgKAAgGIACgNIACgLQACgFAFgGQASgTARAGIAAgFQATAGAKAIQAKAKADAPQAEAOgGANQgIAUgTAFQgHADgHAAQgMAAgLgJgEAhDgMrQgJgFgKgOQgHgKAAgHIACgMIACgMQACgFAFgFQAUgTAPAFIAAgDQAWACAMARQANASgFAVQgFAVgSAJQgKAFgJAAQgKAAgKgGgEAiugO8QgHgEgIgMQgHgKAAgHQgBgDADgJIACgMQACgFAGgGQAJgJAJgDQAQAFASACIAJAAQAJAIAEALQAFAOgDAOQgEAOgKAJQgLAKgPABIgBAAQgPAAgKgIgAf2ySQgMAAgJgHQgIgFgGgJQgHgJgBgHQgBgHACgKQABgHADgEQAFgMALgHQAMgHANACIAAgEQARAEALAKQARAQgCAXQgDAZgVALQgJAEgJAAIgEAAgEAzngbPQgOgHgJgOQgGgKAAgGIACgMIACgLQACgFAGgGQATgTAQAFIAAgEQAWAIAGAGQAJAHAEANQADALgCANQgDAMgIAJQgIAKgMADIgJACQgKAAgKgFgEA0ygcAQgHgFgHgJQgIgKgCgGQgBgHACgLQABgFADgHQAFgLAMgHQALgHANACIAAgDQANABALAIQALAJAFAMQAFANgDAOQgDAOgKAKQgKAJgPACIgEAAQgMAAgKgGgEBD0ge/QgHgFgHgLQgHgKgBgGQgBgEACgJIADgNQADgFAFgGQASgSAQAFIAAgDQAOACALAJQALAJAFAMQAEAOgDAOQgEAOgLAJQgKAIgPABIgBAAQgOAAgLgHgEA7+gfMQgJgFgKgPQgHgKAAgGIACgNIACgLQACgFAFgGQAUgSAPAFIAAgEQAWADAMARQANARgFAVQgFAVgSAKQgKAEgJAAQgKAAgKgFgEAROggsQgJgGgJgOQgHgIAAgHIACgMIACgLQACgFAGgHQATgTAQAGIAAgEQANACALAIQALAJAFANQAFANgDANQgEAOgJAKQgKAJgPABIgFABQgLAAgKgGgEAQQgjKQgMgHgHgMQgGgIgBgIIACgNIACgLQACgFAGgGQASgSAQAFIAAgEQAMABALAIQALAHAFALQAFALgBANQAAANgHAKQgMARgTACIgEAAQgKAAgLgGgEASWglVQgMgEgJgKQgJgJgCgJQgDgMAFgPIAFgKQAGgKAKgFQALgFALABIAAgDQAVAHAJAIQAIAHADAMQADALgCALQgCANgIAJQgIAKgLAEQgFABgGAAQgHAAgIgCg");
	this.shape_3.setTransform(719.0068,-20.6819);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#5B075F").s().p("Egg0AkzQgHgFgHgKQgIgJAAgIQgBgDADgKIACgMQACgFAGgGQASgSAQAFIAAgEQAOACALAJQAMAJAEANQAEANgDAPQgEAOgLAIQgLAJgOAAIgCAAQgOAAgKgHgEgfFAj0QgFgDgKgMQgIgLAAgHIACgNIACgLQACgFAGgGQATgTAQAGIAAgEQANACAMAJQALAJAEAMQAFAOgEAOQgDAOgLAJQgKAJgPAAIgDAAQgNAAgKgHgEgg/Af6QgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAGgGQAUgUAPAGIAAgEQAYADAMAUQANAUgJAWQgIATgRAGQgHADgIAAQgJAAgKgFgA+Bf5QgMgGgIgLQgHgJAAgIIABgOIACgLQACgEAGgHQAUgTAPAGIAAgFQAVAHAIAIQAJAIADAMQADALgCAMQgDANgKALQgKAKgNACIgFAAQgKAAgKgGgA83d5QgIgGgGgKQgIgKAAgHQgBgDADgKIACgMQACgFAFgFQATgTAQAFIAAgDQAQABAMAMQAMALACAPQADANgFAMQgFANgKAHQgLAIgNAAQgOAAgLgHgA6JZ8QgHgFgIgLQgIgKAAgHQAAgDACgKIACgLQACgFAGgGQATgTAQAFIAAgDQANABALAJQALAIAFAMQAFANgDAPQgDAOgLAKQgKAJgPABIgCAAQgOAAgLgHgEhWZAZNQgIgFgHgKQgHgJgBgHQgBgGACgJQAAgGADgGIAIgLQASgSAQAFIAAgFQAUAFAMANQAGAIADAJQAEANgEAOQgEAOgKAIQgKAJgPAAIgDAAQgNAAgJgGgEhSwAYXIAFgLIABgDIABABIANALQgNALgKANQgBgKAEgMgEhZTAVDQgKgGgKgPQgHgJAAgHIACgMIACgLQABgEAGgHQAUgTAPAFIAAgDQAYACAMAUQANAVgJAWQgIASgRAHQgHADgIAAQgJAAgKgFgEhOcAR1QgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAHgGQATgUAQAGIAAgEQAYADAMAUQANAUgKAWQgHATgRAGQgIADgHAAQgKAAgKgFgAhKQUQAKgFALABIAAgDIAKACIgBAAQgTADgRAFIAGgDgEgqgAHLIgUgEIAAgCQAMABAJAFIgBAAgEAvQAEPQgKgGgIgMQgHgJgBgIIACgNIACgLQACgFAGgHIAKgIQAeALAWAFIALACIACAFQAFANgDAOQgEAOgJAJQgKAJgOACIgGAAQgLAAgJgFgEAsTAD2QgOgCgLgLQgKgKgEgNQgDgJAAgGQABgSAOgMQANgMASACIAAgDQANgBANAHQAMAGAHAMQAGALAAAOQgBAOgHALQgIALgNAGQgJAEgJAAIgIgBgEBQUADIQgPgBgqAAQARgRAPAFIAAgDQAPABAMALIAFAEIgHAAgEBP3ABSQgJgGgKgOQgHgKAAgGIACgNIACgLQACgFAFgGQATgRAQAFIAAgDQAYABANAVQAMAUgKAXQgIARgRAHQgIACgHAAQgKAAgJgFgEBK4AAwQgOgIgHgRQgGgRAFgPQAFgPAMgJQAOgKAOACIAAgDQAPABAMALQAMALADAPQACAIgBAMQgBAMgGAJQgJAOgSAEIgKABQgMAAgKgGgEBMegCZQgPgHgKgOQgFgJgBgIIACgMIACgLQACgFAGgGQATgTAQAGIAAgFQAWAIAGAGQAJAHAEANQADALgCAMQgFAagWAIQgGADgHAAQgJAAgJgEgEBKngDtQgGgEgJgMQgHgKAAgGIACgNIACgLQACgFAFgGQASgTARAGIAAgFQATAGAKAIQAKAKADAPQAEAOgGANQgIAUgTAFQgHACgHAAQgMAAgLgIgEA17gK0QgJgFgKgOQgHgKAAgHIACgMIACgMQACgFAFgFQAUgTAPAFIAAgDQAWACAMARQANASgFAVQgFAVgSAJQgKAFgJAAQgKAAgKgGgEA3mgNFQgHgEgIgMQgHgKAAgHQgBgDADgJIACgMQACgFAGgGQAJgJAJgEQAQAGASACIAJAAQAJAIAEALQAFAOgDAOQgEAOgKAJQgLAKgPABIgCAAQgOAAgKgIgEBIugYCQgNgGgDgHIgCgNIgCgKQAAgIAEgHQAGgJAJgFQAKgGAKADIAAgEQAZAIAGAMQAFAHgBANQgBAbgTAIQgFADgHAAQgKAAgMgGgEBYsgdIQgHgFgHgLQgHgKgBgGQgBgEACgJIADgNQADgFAFgGQASgSAQAFIAAgDQAOACALAJQALAJAFAMQAEAOgDAOQgEAOgLAJQgKAIgPABIgCAAQgNAAgLgHgEBQ2gdVQgJgFgKgPQgHgKAAgGIACgNIACgLQACgFAFgGQAUgSAPAFIAAgEQAWADAMARQANARgFAVQgFAVgSAKQgKAEgJAAQgKAAgKgFgEBJygeUQgEgDgBgDQgBgCAAgIIgDgOQAAgHAEgGQAFgKAKgFQAKgGAKADIAAgFQAZAJAHAMQAHANgGATQgEAOgIAGQgFADgIACIgHAAQgRAAgOgMgEBTlggMQgNgGgCgHQgCgEAAgIIgCgLQgBgDADgHQAFgMAJgGQAMgHAKADIAAgEQAYAIAGAKQAIALgDAUQgEAPgIAHQgIAHgLAAQgLAAgMgGgEAlIghTQgMgHgHgMQgGgIgBgIIACgNIACgLQACgFAGgGQASgSAQAFIAAgEQAMABALAIQALAHAFALQAFALgBANQAAANgHAKQgMARgTACIgEAAQgKAAgLgGgEAnOgjeQgMgEgJgKQgJgJgCgJQgDgMAFgPIAFgKQAGgKAKgFQALgFALABIAAgDQAVAHAJAIQAIAHADAMQADALgCALQgCANgIAJQgIAKgLAEQgGABgFAAQgHAAgIgCg");
	this.shape_4.setTransform(585.4266,-32.5735);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#5B075F").s().p("Eg4yAnMQgOgDgLgJQgEgDgBgDIgBgLIgDgLQAAgFACgGQAFgMAJgGQALgIAMAEIAAgEQAZAIAGAMQAEAHAAAMQgBAXgNAJQgIAHgLAAIgHgBgEg5iAkOQgNgCgLgKQgEgCgCgEIAAgKIgDgLQgBgIAFgIQAFgKAKgFQAKgGAJADIAAgEQAaAHAIAQQAEALgDAQQgGAUgOAGQgFACgGAAIgJgBgEg05AigQgGgFgIgKQgHgJgBgIQAAgDACgKIACgMQACgFAGgGQASgSARAFIAAgEQANACAMAJQALAJAEANQAFANgEAPQgEAOgKAIQgLAJgPAAIgBAAQgOAAgLgHgEgzJAhhQgFgDgKgMQgIgLAAgHIACgNIACgLQACgFAFgGQATgTAQAGIAAgEQAOACALAJQALAJAFAMQAEAOgDAOQgEAOgKAJQgLAJgOAAIgDABQgNAAgKgIgEg1EAdnQgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAHgGQATgUAQAGIAAgEQAYADAMAUQANAUgKAWQgHATgRAGQgIAEgHAAQgKAAgKgGgEgx0Ac0QgOAAgOgMQgFgEgBgDIAAgKIgDgLQgBgEADgHQAFgMAJgGQAMgHALADIAAgEQAZAJAHAMQAGAMgFATQgCAJgGAGQgJALgOAAIgEgBgEguNAXpQgHgFgIgLQgIgKAAgHQgBgDADgKIACgLQACgFAGgGQATgTAPAFIAAgDQANABALAJQALAIAFAMQAGANgEAPQgDAOgKAKQgLAJgPABIgBAAQgPAAgKgHgEhqeAW6QgHgFgHgKQgHgJgCgHQAAgGABgJQABgGACgGIAIgLQASgSAQAFIAAgFQAVAFALANQAHAIADAJQAEANgEAOQgEAOgLAIQgKAJgOAAIgEABQgMAAgKgHgEhm1AWEIAFgLIACgCIABAAIANAMQgOAKgKANQgBgJAEgNgEhjeAWVQgNgGgDgIIgCgMIgCgLQAAgIAEgHQAFgKAKgEQAKgGAJADIAAgEQAYAIAIAMQAHAOgFARQgGASgLAGQgGADgIAAQgJAAgMgFgEhhxAUVQgLgFgEgIIgCgMIgCgLQAAgGAEgIQAGgKAJgFQAKgFAKADIAAgFQAYAJAHALQAGAKgDAOQgCAWgPAJQgGADgIAAQgKAAgNgGgEhtYASwQgKgGgKgPQgHgJAAgHIACgMIACgLQABgEAHgHQATgTAQAFIAAgDQAYACAMAUQANAVgKAWQgHASgRAHQgIADgHAAQgKAAgKgFgEhkmASnQgIgDgFgGQgDgFgCgLIgBgNQAAgFAEgLQAGgPAJgIQAOgLANAEIAAgEQASADAKAOQALAPgEASQgCAJgKAQQgHALgFADQgHAFgJAAQgKAAgMgGgEBp/AQpQgLgGgEgHIgCgJQgCgMABgIQACgNAMgIQALgIANACIAAgEQAdAIAFAUQADAJgEANQgDAOgIAIQgIAGgLAAQgKAAgNgFgEhigAPiQgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAGgGQAUgUAPAGIAAgEQAYADAMAUQANAUgJAWQgIATgRAGQgHAEgIAAQgJAAgKgGgA1POBQALgFALABIAAgDIAJACIAAAAQgTADgRAFIAFgDgEBtKAMwQgMgCgLgJQgEgEgCgDIAAgKIgDgLQgBgGAEgJQAGgLAJgFQAKgGAKAEIAAgFQAYAIAHAMQAGAKgCANQgCAWgOAJQgHAFgJAAIgJgCgEAw5AGVQgLgCgMgJIgGgHIAAgKIgDgLQgBgIAFgHQAFgKAJgFQALgGAJADIAAgFQAYAJAHAKQAFAJgBAPQgCAWgOAJQgHAFgJAAIgJgCgEg+lAE4IgTgEIAAgCQALABAKAGIgCgBgAJgDcIgFgHIgBgJIgDgLQgBgIAFgIQAFgKAJgGQALgGAKAEIAAgFQAYAIAHANQAHANgFATQgEALgEAEQgHAIgLACIgGAAQgQAAgPgMgAbMB8QgKgGgJgMQgHgJAAgIIACgNIACgLQACgFAGgHIAKgIQAeALAVAFIAMACIACAFQAEANgDAOQgDAOgKAJQgJAJgPACIgGAAQgKAAgJgFgEBHAABdQgDgCgCgEIgEgWQAAgIAGgKQAFgIAJgFQAKgFAJADIAAgFQAQACALAHQAOAJACANQABAGgCAMQgEAQgIAHQgFAEgKACIgLACQgTAAgPgOgAYPBjQgOgCgLgLQgLgKgEgNQgCgJAAgGQABgSANgMQAOgMASACIAAgDQANgBAMAHQANAGAGAMQAHALgBAOQAAAOgIALQgHALgNAGQgJAEgJAAIgIgBgEAw5ABJQgMgCgLgJQgEgDgCgDQgBgDABgHIgDgMQgCgHAGgIQAFgKAJgFQALgFAJACIAAgEQAYAIAHAKQAFAJgBAPQgCAWgOAJQgHAFgJAAIgJgCgEA8PAA1QgOgBgrAAQASgRAPAFIAAgDQAPABAMALIAEAFIgHgBgEA7ygBAQgIgGgLgOQgHgKAAgGIACgNIACgLQACgFAGgGQASgSARAFIAAgDQAYABANAWQAMAUgKAXQgIARgSAHQgHADgHAAQgKAAgKgGgEA2zgBiQgOgIgGgRQgGgRAFgQQAEgPANgJQANgKAOACIAAgDQAPABAMALQAMALAEAPQACAJgBAMQgCAMgGAJQgJAOgSAEIgKABQgLAAgLgGgEBP5gENIgFgHQgBgDAAgGIgDgLQAAgJAEgIQAGgJAJgFQAKgGAKADIAAgFQAYAIAHANQAHAMgFAVQgFALgDADQgHAIgLACIgGAAQgQAAgPgMgEBQwgGgQgLgCgMgJQgEgDgCgDQgBgDABgHIgDgMQgCgHAGgIQAFgKAJgFQALgGAJADIAAgEQAVAGAIAJQAIALgCAQQgCAWgNAIQgIAGgJAAIgJgCgEBNDgIOQgLgCgMgKIgGgGQgBgDABgHIgDgLQgBgIAEgIQAGgKAJgFQALgGAJADIAAgEQAXAHAHAKQAGAJgBAQQgCAVgNAKQgIAFgJAAIgJgBgEBP+gLNQgNgDgJgIQgEgEAAgDIgBgKIgDgKQAAgHAEgJQAGgKAJgFQALgGAJADIAAgEQAZAJAHAMQAIAOgJAXQgDAHgCADQgDAEgIADQgHACgHAAIgKgBgEAjhgPYQgGgEgIgMQgHgKgBgHQAAgDACgJIACgMQACgFAGgGQAJgJAJgDQAQAFATACIAIAAQAJAIAFALQAFAOgEAOQgDAOgLAJQgKAKgPABIgCAAQgOAAgLgIgEAjlgTLQgJgEgDgFIgDgIQgEgRADgNQAEgLALgGQALgGALACIAAgEQAXAHAIANQAIANgGASQgEASgNAGQgGADgHAAQgLAAgNgGgEA1ngbkQgKgFgDgGIgDgPIgCgLQAAgFADgGQAEgKAKgHQALgHALAEIAAgEQAeAJAFATQACAKgEANQgEAMgGAGQgHAIgOABQgLAAgMgGgEA3ogdyQgLgFgEgGIgDgKQgDgSAAgHQABgKAEgJQADgJAEgEQAIgIATABIAAgDQANACALAJQAKAKADANQABAGAAAHQAAAMgGAMQgFANgIAFQgHAEgJAAQgJAAgMgFgEA0sggHQgOgGgEgIQgBgDgBgJIgCgMIABgLQABgKADgFQAIgMAZgBIAAgEQALABAJAHQAKAHAEAKQAFAKgBAMQgBALgHAJQgIAMgMAEQgFACgFAAIgBAAQgHAAgIgEgEAREgjmQgMgHgIgMQgGgIAAgIIACgNIACgLQABgFAGgGQATgSAQAFIAAgEQAMABAKAIQALAHAFALQAGALgBANQgBANgHAKQgLARgTACIgEAAQgLAAgKgGgEATKglxQgNgEgJgKQgIgJgCgJQgEgMAFgPIAFgKQAGgKALgFQAKgFALABIAAgDQAVAHAJAIQAIAHAEAMQADALgDALQgCANgHAJQgIAKgMAEQgFABgFAAQgIAAgHgCg");
	this.shape_5.setTransform(713.8661,-17.8966);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#5B075F").s().p("EgcYAkzQgHgFgHgKQgIgJAAgIQgBgDADgKIACgMQACgFAGgGQASgSAQAFIAAgEQAOACALAJQAMAJAEANQAEANgDAPQgEAOgLAIQgLAJgOAAIgCAAQgOAAgKgHgEgYxAkXQgEgEAAgDQgBgCAAgHQgDgJAAgFQAAgHAEgGQAFgLAJgFQAKgGAKAEIAAgFQAZAKAHALQAHANgGATQgEAPgJAFQgFAEgIABIgGAAQgRAAgOgMgEgbAAjTIACgNIACgLIACgDQgEAPgBARIgBgFgA5YerQgDgCgCgEIgEgWQAAgIAGgKQAFgIAJgFQAKgFAJADIAAgFQAQACALAHQAOAJACANQABAGgCAMQgEAQgIAHQgFAEgKACIgLABQgSAAgQgNgEhRqAamQgMgGgDgIIgCgMIgCgLQAAgHAEgHQAGgKAJgFQAKgFAKADIAAgFQAYAIAHAMQAFAJgCAPQgDAXgOAIQgGAEgJAAQgKAAgMgGgA1tZ8QgHgFgIgLQgIgKAAgHQAAgDACgKIACgLQACgFAGgGQATgTAQAFIAAgDQANABALAJQALAIAFAMQAFANgDAPQgDAOgLAKQgKAJgPABIgCAAQgOAAgLgHgEhL8AZ3QgOgGgDgIIgCgNIgCgKQgBgGAFgJQAFgJAKgFQAKgGAJADIAAgEQAYAIAHAMQAIAMgFATQgFATgPAGIgJACQgKAAgMgFgEhT5AYnQgJgFgDgEIgDgIQgEgSADgMQAEgLALgGQALgGALACIAAgEQAZAJAGALQAHANgFASQgEARgMAGQgGAEgIAAQgLAAgNgGgEhKfAXoQgMgFgDgIIgCgMIgCgNQAAgFAEgIIAFgHIgBAAQgMAAgMgHQgFgCgEgEQgDgEgCgOIgCgLQAAgFADgGQAEgLAKgGQALgGALADIAAgFQAZAJAHANQAHANgHATQgCAIgEAFIAFABIAAgFQAZAJAHANQAHANgGATQgDAKgFAFQgIAJgNAAIgCAAQgJAAgMgFgEgrjAWRQgCgCgCgEIgBgKIgDgLQAAgHAEgJQAGgJAJgFQAKgGAKADIAAgFQAXAIAHAKQAIANgEASQgDARgLAIQgFADgJABIgFAAQgSAAgOgNgEgtUAV+QgNAAgPgLIgFgHIgBgKIgDgMQAAgEACgHQAFgMAJgGQAMgHALADIAAgEQAZAJAGAMQAHAMgFAUQgDAJgFAFQgIAKgPAAIgEAAgEhU3AVDQgKgGgKgPQgHgJAAgHIACgMIACgLQABgEAGgHQAUgTAPAFIAAgDQAYACAMAUQANAVgJAWQgIASgRAHQgHADgHAAQgKAAgKgFgEhLvAUvQgNgCgMgJQgFgEgBgDIAAgKIgDgLQgCgIAGgIQAFgKAJgFQALgGAJADIAAgEQAYAIAGAKQAIALgDASQgEARgKAIQgIAGgKAAIgHgBgEgmgATJQgZgBgLgVQgFgJgDgSQgDgQACgHQADgNALgHQALgIAMACIAAgEQAXAJAIAJQAIAKADATQADARgEAOQgFARgOAFQgFACgFAAIgEAAgEhKAAR1QgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAHgGQATgUAQAGIAAgEQAYADAMAUQANAUgKAWQgHATgRAGQgHADgIAAQgKAAgKgFgADRQUQAKgFALABIAAgDIAKACIgBAAQgTADgQAFIAFgDgEgm6AO/QgNgFgDgJIgCgMIgCgLQAAgHAEgHQAFgKAKgFQAKgFAJADIAAgFQAYAIAHALQAIAOgFATQgFARgMAGQgGADgHAAQgJAAgNgFgEgmEAHLIgUgEIAAgCQAMABAJAFIgBAAgEBUwADIQgPgBgqAAQARgRAPAFIAAgDQAPABAMALIAFAEIgHAAgEBUTABSQgJgGgKgOQgHgKAAgGIACgNIACgLQACgFAFgGQATgRAQAFIAAgDQAYABANAVQAMAUgKAXQgIARgRAHQgHACgHAAQgLAAgJgFgEBPUAAwQgOgIgHgRQgGgRAFgPQAFgPAMgJQAOgKAOACIAAgDQAPABAMALQAMALADAPQACAIgBAMQgBAMgGAJQgJAOgSAEIgKABQgMAAgKgGgEA8CgNFQgHgEgIgMQgHgKAAgHQgBgDADgJIACgMQACgFAGgGQAJgJAJgEQAQAGASACIAJAAQAJAIAEALQAFAOgDAOQgEAOgKAJQgLAKgPABIgBAAQgPAAgKgIgEA8RgOuQgSgGgGgJQgDgEgBgIQgCgNACgNQABgJAEgGQAIgKAYgBIAAgEQANACALAJQAKAJADANQAFASgLAQQgIAKgOAGIgJACQgEAAgFgCgEA5IgRIQgLgFgCgIIgDgMIgCgLQAAgGAEgHQAFgKAKgGQAKgFAKADIAAgFQAYAHAHANQAHAMgFAVQgEALgGAHQgIAHgOAAQgKAAgMgGgEA9MgStIgFgGIgEgWQgBgJAGgJQAGgJAJgEQAJgFAJADIAAgFQAhAEAIAUQAFALgEARQgEAOgIAGQgGAFgKABIgIABQgTAAgQgNgEBQFgdlQgFgDgBgEQgBgDABgHIgDgLQgBgEADgIQAHgMAIgFQAKgHALADIAAgFQAQACAKAGQAOAIADANQACAIgCALQgEARgHAGQgFAFgLACIgLABQgTAAgPgNgEBMPgeUQgEgDAAgDQgBgCAAgIIgDgOQAAgHAEgGQAFgKAJgFQALgGAJADIAAgFQAZAJAHAMQAHANgFATQgEAOgIAGQgFADgJACIgGAAQgRAAgPgMgEBOeggDIgFgGQgBgDAAgHIgDgLQgBgGAFgKQAGgKAIgFQAKgGALADIAAgEQAYAIAHANQAHAMgFAUQgFALgDAEQgHAIgLABIgGABQgQAAgPgNgEApkghTQgMgHgHgMQgGgIgBgIIACgNIACgLQACgFAGgGQASgSAQAFIAAgEQAMABALAIQALAHAFALQAFALgBANQAAANgHAKQgMARgTACIgEAAQgKAAgLgGgEArqgjeQgMgEgJgKQgJgJgCgJQgDgMAFgPIAFgKQAGgKAKgFQALgFALABIAAgDQAVAHAJAIQAIAHADAMQADALgCALQgCANgIAJQgIAKgLAEQgFABgGAAQgHAAgIgCg");
	this.shape_6.setTransform(557.0023,-32.5735);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#5B075F").s().p("AAJADIgSgDIAAgCQAKABAJAEIgBAAg");
	this.shape_7.setTransform(312.3875,13.0625);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#5B075F").s().p("EgcYAkzQgHgFgHgKQgIgJAAgIQgBgDADgKIACgMQACgFAGgGQASgSAQAFIAAgEQAOACALAJQAMAJAEANQAEANgDAPQgEAOgLAIQgLAJgOAAIgCAAQgOAAgKgHgEgbAAjTIACgNIACgLIACgDQgEAPgBARIgBgFgA1tZ8QgHgFgIgLQgIgKAAgHQAAgDACgKIACgLQACgFAGgGQATgTAQAFIAAgDQANABALAJQALAIAFAMQAFANgDAPQgDAOgLAKQgKAJgPABIgCAAQgOAAgLgHgEhU3AVDQgKgGgKgPQgHgJAAgHIACgMIACgLQABgEAGgHQAUgTAPAFIAAgDQAYACAMAUQANAVgJAWQgIASgRAHQgHADgHAAQgKAAgKgFgEhKAAR1QgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAHgGQATgUAQAGIAAgEQAYADAMAUQANAUgKAWQgHATgRAGQgHADgIAAQgKAAgKgFgADRQUQAKgFALABIAAgDIAKACIgBAAQgTADgQAFIAFgDgEgmEAHLIgUgEIAAgCQAMABAJAFIgBAAgEBUwADIQgPgBgqAAQARgRAPAFIAAgDQAPABAMALIAFAEIgHAAgEBUTABSQgJgGgKgOQgHgKAAgGIACgNIACgLQACgFAFgGQATgRAQAFIAAgDQAYABANAVQAMAUgKAXQgIARgRAHQgHACgHAAQgLAAgJgFgEBPUAAwQgOgIgHgRQgGgRAFgPQAFgPAMgJQAOgKAOACIAAgDQAPABAMALQAMALADAPQACAIgBAMQgBAMgGAJQgJAOgSAEIgKABQgMAAgKgGgEA8CgNFQgHgEgIgMQgHgKAAgHQgBgDADgJIACgMQACgFAGgGQAJgJAJgEQAQAGASACIAJAAQAJAIAEALQAFAOgDAOQgEAOgKAJQgLAKgPABIgBAAQgPAAgKgIgEApkghTQgMgHgHgMQgGgIgBgIIACgNIACgLQACgFAGgGQASgSAQAFIAAgEQAMABALAIQALAHAFALQAFALgBANQAAANgHAKQgMARgTACIgEAAQgKAAgLgGgEArqgjeQgMgEgJgKQgJgJgCgJQgDgMAFgPIAFgKQAGgKAKgFQALgFALABIAAgDQAVAHAJAIQAIAHADAMQADALgCALQgCANgIAJQgIAKgLAEQgFABgGAAQgHAAgIgCg");
	this.shape_8.setTransform(557.0023,-32.5735);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#5B075F").s().p("EgcYAkzQgHgFgHgKQgIgJAAgIQgBgDADgKIACgMQACgFAGgGQASgSAQAFIAAgEQAOACALAJQAMAJAEANQAEANgDAPQgEAOgLAIQgLAJgOAAIgCAAQgOAAgKgHgEgapAj0QgFgDgKgMQgIgLAAgHIACgNIACgLQACgFAGgGQATgTAQAGIAAgEQANACAMAJQALAJAEAMQAFAOgEAOQgDAOgLAJQgKAJgPAAIgDAAQgNAAgKgHgA8jf6QgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAGgGQAUgUAPAGIAAgEQAYADAMAUQANAUgJAWQgIATgRAGQgHADgHAAQgKAAgKgFgA1tZ8QgHgFgIgLQgIgKAAgHQAAgDACgKIACgLQACgFAGgGQATgTAQAFIAAgDQANABALAJQALAIAFAMQAFANgDAPQgDAOgLAKQgKAJgPABIgCAAQgOAAgLgHgEhR9AZNQgIgFgHgKQgHgJgBgHQgBgGACgJQAAgGADgGIAIgLQASgSAQAFIAAgFQAUAFAMANQAGAIADAJQAEANgEAOQgEAOgKAIQgKAJgPAAIgDAAQgMAAgKgGgEhOUAYXIAFgLIACgDIAAABIANALQgNALgKANQgBgKAEgMgEhU3AVDQgKgGgKgPQgHgJAAgHIACgMIACgLQABgEAGgHQAUgTAPAFIAAgDQAYACAMAUQANAVgJAWQgIASgRAHQgHADgHAAQgKAAgKgFgEhKAAR1QgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAHgGQATgUAQAGIAAgEQAYADAMAUQANAUgKAWQgHATgRAGQgHADgIAAQgKAAgKgFgADRQUQAKgFALABIAAgDIAKACIgBAAQgTADgQAFIAFgDgEgmEAHLIgUgEIAAgCQAMABAJAFIgBAAgEAzsAEPQgKgGgIgMQgHgJgBgIIACgNIACgLQACgFAGgHIAKgIQAeALAWAFIALACIACAFQAFANgDAOQgEAOgJAJQgKAJgOACIgGAAQgLAAgJgFgEAwvAD2QgOgCgLgLQgKgKgEgNQgDgJAAgGQABgSAOgMQANgMASACIAAgDQANgBANAHQAMAGAHAMQAGALAAAOQgBAOgHALQgIALgNAGQgIAEgJAAIgJgBgEBUwADIQgPgBgqAAQARgRAPAFIAAgDQAPABAMALIAFAEIgHAAgEBUTABSQgJgGgKgOQgHgKAAgGIACgNIACgLQACgFAFgGQATgRAQAFIAAgDQAYABANAVQAMAUgKAXQgIARgRAHQgHACgHAAQgLAAgJgFgEBPUAAwQgOgIgHgRQgGgRAFgPQAFgPAMgJQAOgKAOACIAAgDQAPABAMALQAMALADAPQACAIgBAMQgBAMgGAJQgJAOgSAEIgKABQgMAAgKgGgEA8CgNFQgHgEgIgMQgHgKAAgHQgBgDADgJIACgMQACgFAGgGQAJgJAJgEQAQAGASACIAJAAQAJAIAEALQAFAOgDAOQgEAOgKAJQgLAKgPABIgBAAQgPAAgKgIgEApkghTQgMgHgHgMQgGgIgBgIIACgNIACgLQACgFAGgGQASgSAQAFIAAgEQAMABALAIQALAHAFALQAFALgBANQAAANgHAKQgMARgTACIgEAAQgKAAgLgGgEArqgjeQgMgEgJgKQgJgJgCgJQgDgMAFgPIAFgKQAGgKAKgFQALgFALABIAAgDQAVAHAJAIQAIAHADAMQADALgCALQgCANgIAJQgIAKgLAEQgFABgGAAQgHAAgIgCg");
	this.shape_9.setTransform(557.0023,-32.5735);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#5B075F").s().p("Egg0AkzQgHgFgHgKQgIgJAAgIQgBgDADgKIACgMQACgFAGgGQASgSAQAFIAAgEQAOACALAJQAMAJAEANQAEANgDAPQgEAOgLAIQgLAJgOAAIgCAAQgOAAgKgHgEgfFAj0QgFgDgKgMQgIgLAAgHIACgNIACgLQACgFAGgGQATgTAQAGIAAgEQANACAMAJQALAJAEAMQAFAOgEAOQgDAOgLAJQgKAJgPAAIgDAAQgNAAgKgHgEgg/Af6QgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAGgGQAUgUAPAGIAAgEQAYADAMAUQANAUgJAWQgIATgRAGQgHADgIAAQgJAAgKgFgA+Bf5QgMgGgIgLQgHgJAAgIIABgOIACgLQACgEAGgHQAUgTAPAGIAAgFQAVAHAIAIQAJAIADAMQADALgCAMQgDANgKALQgKAKgNACIgFAAQgKAAgKgGgA83d5QgIgGgGgKQgIgKAAgHQgBgDADgKIACgMQACgFAFgFQATgTAQAFIAAgDQAQABAMAMQAMALACAPQADANgFAMQgFANgKAHQgLAIgNAAQgOAAgLgHgA6JZ8QgHgFgIgLQgIgKAAgHQAAgDACgKIACgLQACgFAGgGQATgTAQAFIAAgDQANABALAJQALAIAFAMQAFANgDAPQgDAOgLAKQgKAJgPABIgCAAQgOAAgLgHgEhWZAZNQgIgFgHgKQgHgJgBgHQgBgGACgJQAAgGADgGIAIgLQASgSAQAFIAAgFQAUAFAMANQAGAIADAJQAEANgEAOQgEAOgKAIQgKAJgPAAIgDAAQgNAAgJgGgEhSwAYXIAFgLIABgDIABABIANALQgNALgKANQgBgKAEgMgEhZTAVDQgKgGgKgPQgHgJAAgHIACgMIACgLQABgEAGgHQAUgTAPAFIAAgDQAYACAMAUQANAVgJAWQgIASgRAHQgHADgIAAQgJAAgKgFgEhOcAR1QgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAHgGQATgUAQAGIAAgEQAYADAMAUQANAUgKAWQgHATgRAGQgIADgHAAQgKAAgKgFgAhKQUQAKgFALABIAAgDIAKACIgBAAQgTADgRAFIAGgDgEgqgAHLIgUgEIAAgCQAMABAJAFIgBAAgEAvQAEPQgKgGgIgMQgHgJgBgIIACgNIACgLQACgFAGgHIAKgIQAeALAWAFIALACIACAFQAFANgDAOQgEAOgJAJQgKAJgOACIgGAAQgLAAgJgFgEAsTAD2QgOgCgLgLQgKgKgEgNQgDgJAAgGQABgSAOgMQANgMASACIAAgDQANgBANAHQAMAGAHAMQAGALAAAOQgBAOgHALQgIALgNAGQgJAEgJAAIgIgBgEBQUADIQgPgBgqAAQARgRAPAFIAAgDQAPABAMALIAFAEIgHAAgEBP3ABSQgJgGgKgOQgHgKAAgGIACgNIACgLQACgFAFgGQATgRAQAFIAAgDQAYABANAVQAMAUgKAXQgIARgRAHQgIACgHAAQgKAAgJgFgEBK4AAwQgOgIgHgRQgGgRAFgPQAFgPAMgJQAOgKAOACIAAgDQAPABAMALQAMALADAPQACAIgBAMQgBAMgGAJQgJAOgSAEIgKABQgMAAgKgGgEBMegCZQgPgHgKgOQgFgJgBgIIACgMIACgLQACgFAGgGQATgTAQAGIAAgFQAWAIAGAGQAJAHAEANQADALgCAMQgFAagWAIQgGADgHAAQgJAAgJgEgEBKngDtQgGgEgJgMQgHgKAAgGIACgNIACgLQACgFAFgGQASgTARAGIAAgFQATAGAKAIQAKAKADAPQAEAOgGANQgIAUgTAFQgHACgHAAQgMAAgLgIgEA17gK0QgJgFgKgOQgHgKAAgHIACgMIACgMQACgFAFgFQAUgTAPAFIAAgDQAWACAMARQANASgFAVQgFAVgSAJQgKAFgJAAQgKAAgKgGgEA3mgNFQgHgEgIgMQgHgKAAgHQgBgDADgJIACgMQACgFAGgGQAJgJAJgEQAQAGASACIAJAAQAJAIAEALQAFAOgDAOQgEAOgKAJQgLAKgPABIgCAAQgOAAgKgIgEBYsgdIQgHgFgHgLQgHgKgBgGQgBgEACgJIADgNQADgFAFgGQASgSAQAFIAAgDQAOACALAJQALAJAFAMQAEAOgDAOQgEAOgLAJQgKAIgPABIgCAAQgNAAgLgHgEBQ2gdVQgJgFgKgPQgHgKAAgGIACgNIACgLQACgFAFgGQAUgSAPAFIAAgEQAWADAMARQANARgFAVQgFAVgSAKQgKAEgJAAQgKAAgKgFgEAlIghTQgMgHgHgMQgGgIgBgIIACgNIACgLQACgFAGgGQASgSAQAFIAAgEQAMABALAIQALAHAFALQAFALgBANQAAANgHAKQgMARgTACIgEAAQgKAAgLgGgEAnOgjeQgMgEgJgKQgJgJgCgJQgDgMAFgPIAFgKQAGgKAKgFQALgFALABIAAgDQAVAHAJAIQAIAHADAMQADALgCALQgCANgIAJQgIAKgLAEQgGABgFAAQgHAAgIgCg");
	this.shape_10.setTransform(585.4266,-32.5735);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#5B075F").s().p("Eg5vAmuQgMgFgJgLQgIgJgCgIQgCgLAEgOIAFgKQAGgKALgFQAKgFALABIAAgDQAVAHAIAHQAJAHADANQAEALgDAMQgCAMgIAKQgIAJgMAEIgJABQgIAAgJgDgEg1sAi8QgHgFgHgKQgIgJAAgIQgBgDADgKIACgMQACgFAGgGQASgSAQAFIAAgEQAOACALAJQAMAJAEANQAEANgDAPQgEAOgLAIQgLAJgOAAIgCAAQgOAAgKgHgEgz9Ah9QgFgDgKgMQgIgLAAgHIACgNIACgLQACgFAGgGQATgTAQAGIAAgEQANACAMAJQALAJAEAMQAFAOgEAOQgDAOgLAJQgKAJgPAAIgDAAQgNAAgKgHgEg13AeDQgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAGgGQAUgUAPAGIAAgEQAYADAMAUQANAUgJAWQgIATgRAGQgHADgIAAQgJAAgKgFgEgy5AeCQgMgGgIgLQgHgJAAgIIABgOIACgLQACgEAGgHQAUgTAPAGIAAgFQAVAHAIAIQAJAIADAMQADALgCAMQgDANgKALQgKAKgNACIgEAAQgLAAgKgGgEgxvAcCQgIgGgGgKQgIgKAAgHQgBgDADgKIACgMQACgFAFgFQATgTAQAFIAAgDQAQABAMAMQAMALACAPQADANgFAMQgFANgKAHQgLAIgNAAQgOAAgLgHgEgvBAYFQgHgFgIgLQgIgKAAgHQAAgDACgKIACgLQACgFAGgGQATgTAQAFIAAgDQANABALAJQALAIAFAMQAFANgDAPQgDAOgLAKQgKAJgPABIgCAAQgOAAgLgHgEhrRAXWQgIgFgHgKQgHgJgBgHQgBgGACgJQAAgGADgGIAIgLQASgSAQAFIAAgFQAUAFAMANQAGAIADAJQAEANgEAOQgEAOgKAIQgKAJgPAAIgDAAQgMAAgKgGgEhnoAWgIAFgLIACgCIAAAAIANAMQgNAKgKANQgBgKAEgMgEhuLATMQgKgGgKgPQgHgJAAgHIACgMIACgLQABgEAGgHQAUgTAPAFIAAgDQAYACAMAUQANAVgJAWQgIASgRAHQgHADgIAAQgJAAgKgFgEBtqASMQgOgGgJgNQgFgJgBgIIACgNIACgLQACgEAGgHQASgSARAFIAAgEQAVAHAIAHQAJAIADAMQADAMgCAMQgDANgJAJQgIAJgMADIgJABQgJAAgKgFgEhjUAP+QgKgGgKgOQgHgJAAgHIACgNIACgLQABgEAHgGQATgUAQAGIAAgEQAYADAMAUQANAUgKAWQgHATgRAGQgIADgHAAQgKAAgKgFgEBqQAPQQgMgFgJgKQgIgJgCgJQgDgJAFgPIAFgLQAGgJALgGQAKgFALABIAAgCQANABAMAIQALAJAEANQAFAMgDAOQgCAOgKAJQgIAJgMADIgIABQgIAAgIgEgA2COdQAKgFALABIAAgDIAKACIgBAAQgTADgQAFIAFgDgEg/YAFUIgUgEIAAgCQAMABAJAGIgBgBgEA3eADVQgFgEgKgMQgIgMAAgFIACgNIACgLQACgFAGgGQATgTAQAGIAAgEQANABALAJQALAJAFAMQAFANgDAPQgEAOgKAJQgLAJgPABIgBAAQgOAAgLgHgEA67ACdQgSgEgOgUQgGgKAAgHIACgMIACgLQACgGAGgFQASgUAQAGIAAgDQAPABAMALQAMALADAOQAGAXgQASQgHAJgLADQgHADgHAAIgIgBgAaYCYQgKgGgIgMQgHgJgBgIIACgNIACgLQACgFAGgHQASgSARAFIAAgDQANABALAJQALAJAFAMQAFANgDAOQgEAOgJAJQgKAJgOACIgGAAQgLAAgJgFgAXbB/QgOgCgLgLQgKgKgEgNQgDgJAAgGQABgSAOgMQANgMASACIAAgDQANgBANAHQAMAGAHAMQAGALAAAOQgBAOgHALQgIALgNAGQgJAEgIAAIgJgBgAbNgTQgPgFgKgQQgGgJAAgIIACgMIACgMQADgGAFgEQARgTARAFIAAgEQAVAHAIAHQAJAIADANQAEAMgDAMQgFAXgTAIQgIAEgIAAQgIAAgJgEgEA6/gAkQgJgGgKgOQgHgKAAgGIACgNIACgLQACgFAFgGQATgSAQAFIAAgDQAYABANAWQAMAUgKAXQgIARgRAHQgHACgHAAQgLAAgJgFgEA2AgBGQgOgIgHgRQgGgRAFgQQAFgPAMgJQAOgKAOACIAAgDQAPABAMALQAMALADAPQACAJgBAMQgBAMgGAJQgJAOgSAEIgKABQgMAAgKgGgAYKhVQgMgGgIgMQgGgKAAgHIACgNIACgLQACgFAGgFQATgTAPAFIAAgDQANABAKAHQAKAIAGALQAFALgBANQgBANgHAKQgMARgRABIgEABQgLAAgLgHgEA3mgEQQgPgHgKgOQgFgJgBgIIACgMIACgLQACgFAGgGQATgTAQAGIAAgFQAWAIAGAGQAJAHAEANQADALgCAMQgFAagWAIQgGADgHAAQgIAAgKgEgEA1vgFkQgGgEgJgMQgHgKAAgGIACgNIACgLQACgFAFgGQASgTARAGIAAgFQATAGAKAIQAKAKADAPQAEAOgGANQgIAUgTAFQgHADgHAAQgMAAgLgJgEAhDgMrQgJgFgKgOQgHgKAAgHIACgMIACgMQACgFAFgFQAUgTAPAFIAAgDQAWACAMARQANASgFAVQgFAVgSAJQgKAFgJAAQgKAAgKgGgEAiugO8QgHgEgIgMQgHgKAAgHQgBgDADgJIACgMQACgFAGgGQAJgJAJgDQAQAFASACIAJAAQAJAIAEALQAFAOgDAOQgEAOgKAJQgLAKgPABIgBAAQgPAAgKgIgAf2ySQgMAAgJgHQgIgFgGgJQgHgJgBgHQgBgHACgKQABgHADgEQAFgMALgHQAMgHANACIAAgEQARAEALAKQARAQgCAXQgDAZgVALQgJAEgJAAIgEAAgEAzngbPQgOgHgJgOQgGgKAAgGIACgMIACgLQACgFAGgGQATgTAQAFIAAgEQAWAIAGAGQAJAHAEANQADALgCANQgDAMgIAJQgIAKgMADIgJACQgKAAgKgFgEA0ygcAQgHgFgHgJQgIgKgCgGQgBgHACgLQABgFADgHQAFgLAMgHQALgHANACIAAgDQANABALAIQALAJAFAMQAFANgDAOQgDAOgKAKQgKAJgPACIgEAAQgMAAgKgGgEBD0ge/QgHgFgHgLQgHgKgBgGQgBgEACgJIADgNQADgFAFgGQASgSAQAFIAAgDQAOACALAJQALAJAFAMQAEAOgDAOQgEAOgLAJQgKAIgPABIgBAAQgOAAgLgHgEA7+gfMQgJgFgKgPQgHgKAAgGIACgNIACgLQACgFAFgGQAUgSAPAFIAAgEQAWADAMARQANARgFAVQgFAVgSAKQgKAEgJAAQgKAAgKgFgEAROggsQgJgGgJgOQgHgIAAgHIACgMIACgLQACgFAGgHQATgTAQAGIAAgEQANACALAIQALAJAFANQAFANgDANQgEAOgJAKQgKAJgPABIgFABQgLAAgKgGgEAQQgjKQgMgHgHgMQgGgIgBgIIACgNIACgLQACgFAGgGQASgSAQAFIAAgEQAMABALAIQALAHAFALQAFALgBANQAAANgHAKQgMARgTACIgEAAQgKAAgLgGgEASWglVQgMgEgJgKQgJgJgCgJQgDgMAFgPIAFgKQAGgKAKgFQALgFALABIAAgDQAVAHAJAIQAIAHADAMQADALgCALQgCANgIAJQgIAKgLAEQgFABgGAAQgHAAgIgCg");
	this.shape_11.setTransform(719.0068,-20.6819);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.shape}]},3).to({state:[{t:this.shape_1}]},4).to({state:[{t:this.shape_2}]},3).to({state:[{t:this.shape_3}]},5).to({state:[{t:this.shape_4}]},6).to({state:[{t:this.shape_5}]},6).to({state:[{t:this.shape_6}]},5).to({state:[{t:this.shape_7}]},7).to({state:[{t:this.shape_8}]},7).to({state:[{t:this.shape_9}]},6).to({state:[{t:this.shape_10}]},7).to({state:[{t:this.shape_11}]},7).to({state:[{t:this.shape_2}]},5).to({state:[{t:this.shape}]},4).to({state:[{t:this.instance}]},4).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(11.1,-268.8,1416,501.8);


(lib.covid = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Tween_2
	this.instance = new lib.Tween2("synched",0);
	this.instance.setTransform(836.85,374.7,0.8493,0.8493);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:833.75},19,cjs.Ease.quadInOut).to({y:371.6},33,cjs.Ease.quadInOut).to({x:836.85,y:374.7},34,cjs.Ease.quadInOut).to({x:833.75},35,cjs.Ease.quadInOut).wait(1));

	// Tween_4
	this.instance_1 = new lib.Tween4("synched",0);
	this.instance_1.setTransform(586.35,51.85,0.7006,0.7001);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:583.25},19,cjs.Ease.quadInOut).to({y:48.75},33,cjs.Ease.quadInOut).to({x:586.35,y:51.85},34,cjs.Ease.quadInOut).to({x:583.25},35,cjs.Ease.quadInOut).wait(1));

	// Tween_6
	this.instance_2 = new lib.Tween6("synched",0);
	this.instance_2.setTransform(1301.45,302.1,0.5422,0.5422,0,0,0,0,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:299},33,cjs.Ease.quadInOut).to({x:1304.55,y:302.1},47,cjs.Ease.quadInOut).to({x:1301.45},41,cjs.Ease.quadInOut).wait(1));

	// Tween_6
	this.instance_3 = new lib.Tween6("synched",0);
	this.instance_3.setTransform(1096.55,186.9,0.5422,0.5422,0,0,0,0.1,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1).to({regX:-0.1,regY:-0.1,x:1096.35,y:186.7},0).wait(1).to({x:1096.25},0).wait(1).to({x:1096.2},0).wait(1).to({x:1096.1},0).wait(1).to({x:1096.05},0).wait(1).to({startPosition:0},0).wait(1).to({x:1096},0).wait(1).to({startPosition:0},0).wait(1).to({regX:0,regY:0.1,x:1096.1,y:186.9},0).to({y:183.8},33,cjs.Ease.quadInOut).to({x:1099.2,y:186.9},34,cjs.Ease.quadInOut).to({x:1096.1},45,cjs.Ease.quadInOut).wait(1));

	// Tween_8
	this.instance_4 = new lib.Tween8("synched",0);
	this.instance_4.setTransform(135.15,435.85,0.6143,0.6143,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1).to({regX:-0.1,regY:-0.1,x:134.95,y:435.7},0).wait(1).to({x:134.85},0).wait(1).to({x:134.8},0).wait(1).to({x:134.75},0).wait(1).to({x:134.7},0).wait(1).to({x:134.65,y:435.65},0).wait(1).to({startPosition:0},0).wait(1).to({x:134.6},0).wait(1).to({regX:0.1,regY:0,x:134.75,y:435.8},0).to({y:432.7},33,cjs.Ease.quadInOut).to({x:137.85,y:435.8},34,cjs.Ease.quadInOut).to({x:134.75},45,cjs.Ease.quadInOut).wait(1));

	// Tween_11
	this.instance_5 = new lib.Tween11("synched",0);
	this.instance_5.setTransform(318.9,435.85,0.6142,0.6142,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({y:432.75},33,cjs.Ease.quadInOut).to({x:322,y:435.85},34,cjs.Ease.quadInOut).to({x:318.9},54,cjs.Ease.quadInOut).wait(1));

	// Tween_12
	this.instance_6 = new lib.Tween12("synched",0);
	this.instance_6.setTransform(450.05,316.35,0.6615,0.6615,0,0,0,0,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({y:319.45},23,cjs.Ease.quadInOut).to({y:313.25},33,cjs.Ease.quadInOut).to({x:453.15,y:316.35},39,cjs.Ease.quadInOut).to({x:450.05},26,cjs.Ease.quadInOut).wait(1));

	// Tween_16
	this.instance_7 = new lib.Tween16("synched",0);
	this.instance_7.setTransform(940,2.05,0.6545,0.6545);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({y:-1.05},33,cjs.Ease.quadInOut).to({x:943.1,y:2.05},34,cjs.Ease.quadInOut).to({x:940},54,cjs.Ease.quadInOut).wait(1));

	// Tween_1
	this.instance_8 = new lib.Tween1("synched",0);
	this.instance_8.setTransform(299.25,553.2,0.4116,0.4113,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({y:546.9},21).to({x:296.15,y:550.1},22).to({y:556.3},24).to({x:302.35,y:553.2},24).to({x:296.15,y:556.3},30).wait(1));

	// Tween_3
	this.instance_9 = new lib.Tween3("synched",0);
	this.instance_9.setTransform(450,587.4,0.4797,0.48,0,0,0,0.7,1);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({x:453.1,y:590.5},21).to({x:450,y:593.6},22).to({x:446.9,y:590.5},24).to({x:450,y:587.4},24).to({x:453.1,y:590.5},17).to({x:450,y:587.4},13).wait(1));

	// Tween_9
	this.instance_10 = new lib.Tween9("synched",0);
	this.instance_10.setTransform(52.05,424.65,0.432,0.432,0,0,0,0.7,0.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({x:55.15,y:427.75},21).to({x:52.05,y:430.85},22).to({y:427.75},24).to({x:55.15},20).to({x:52.05,y:430.85},18).to({y:427.75},16).wait(1));

	// Tween_5
	this.instance_11 = new lib.Tween5("synched",0);
	this.instance_11.setTransform(1021.3,93.5,0.3624,0.3622,0,0,0,0.1,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({x:1024.4,y:96.6},21).to({x:1021.3,y:99.7},22).to({y:96.6},24).to({x:1024.4},20).to({x:1021.3,y:99.7},18).to({y:96.6},16).wait(1));

	// Tween_13
	this.instance_12 = new lib.Tween13("synched",0);
	this.instance_12.setTransform(737.15,283.6,0.3997,0.3995,0,0,0,0.1,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_12).to({x:740.25,y:286.7},21).to({x:737.15,y:289.8},22).to({y:286.7},24).to({x:740.25},20).to({x:737.15,y:289.8},18).to({y:286.7},16).wait(1));

	// Tween_5
	this.instance_13 = new lib.Tween5("synched",0);
	this.instance_13.setTransform(861.15,69.35,0.3624,0.3622,0,0,0,0.1,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_13).to({x:858.05},21).to({y:72.45},22).to({x:854.95},24).to({y:69.35},20).to({x:858.05},18).to({y:66.25},16).wait(1));

	// Tween_6
	this.instance_14 = new lib.Tween6("synched",0);
	this.instance_14.setTransform(1278.95,407.9,0.2092,0.2092);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).to({x:1275.85},21).to({y:411},22).to({x:1272.75},24).to({y:407.9},20).to({x:1275.85},18).to({y:404.8},16).wait(1));

	// Tween_7
	this.instance_15 = new lib.Tween7("synched",0);
	this.instance_15.setTransform(1054.05,243.6,0.2661,0.2659,0,0,0,0.2,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({x:1050.95},21).to({y:246.7},22).to({x:1047.85},24).to({y:243.6},20).to({x:1050.95},18).to({y:240.5},16).wait(1));

	// Tween_5
	this.instance_16 = new lib.Tween5("synched",0);
	this.instance_16.setTransform(1021.3,15.7,0.3624,0.3622,0,0,0,0.1,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_16).to({x:1018.2,y:18.8},21).to({y:21.9},22).to({x:1015.1},24).to({startPosition:0},20).to({x:1021.3},18).to({x:1018.2},16).wait(1));

	// Tween_10
	this.instance_17 = new lib.Tween10("synched",0);
	this.instance_17.setTransform(156.3,313.15,0.5185,0.5182,0,0,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_17).to({x:153.2,y:316.25},21).to({y:319.35},22).to({x:150.1},24).to({startPosition:0},20).to({x:156.3},18).to({x:153.2},16).wait(1));

	// Tween_15
	this.instance_18 = new lib.Tween15("synched",0);
	this.instance_18.setTransform(643.95,252.45,0.6278,0.6278);

	this.timeline.addTween(cjs.Tween.get(this.instance_18).to({x:640.85,y:255.55},21).to({y:258.65},22).to({x:637.75},24).to({startPosition:0},20).to({x:643.95},18).to({x:640.85},16).wait(1));

	// Tween_6
	this.instance_19 = new lib.Tween6("synched",0);
	this.instance_19.setTransform(1241.65,314.3,0.2217,0.2217);

	this.timeline.addTween(cjs.Tween.get(this.instance_19).to({x:1244.75},21).to({y:311.2},22).to({x:1241.65},24).to({y:314.3},20).to({y:317.4},18).to({y:314.3},16).wait(1));

	// Tween_14
	this.instance_20 = new lib.Tween14("synched",0);
	this.instance_20.setTransform(673.3,345.5,0.4367,0.4367);

	this.timeline.addTween(cjs.Tween.get(this.instance_20).to({x:676.4},21).to({y:342.4},22).to({x:673.3},24).to({y:345.5},20).to({y:348.6},18).to({y:345.5},16).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(29.2,-34.9,1303.5,652.8);


// stage content:
(lib.pandemic = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// spots
	this.instance = new lib.covidspots();
	this.instance.setTransform(339.95,556.15,1,1,0,0,0,85.4,85.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// covid
	this.instance_1 = new lib.covid();
	this.instance_1.setTransform(942.9,508.2,1,1,0,0,0,546.8,321.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(1225.7,695.1,500,103.60000000000002);
// library properties:
lib.properties = {
	id: 'A44C7C26311C2E4EAB9F5D6F36832384',
	width: 1920,
	height: 1080,
	fps: 24,
	color: "#FFFFFF",
	opacity: 0.00,
	manifest: [
		{src:"images/CachedBmp_75.png", id:"CachedBmp_75"},
		{src:"images/pandemic_atlas_1.png", id:"pandemic_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['A44C7C26311C2E4EAB9F5D6F36832384'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;